### ISSUE TITLE
URL parsing in posts is not working properly

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#58] opened 2019-08-05 20:22 UTC
https://community.mybb.com/thread-219143-post-1331991.html#pid1331991

**Comment by Eldenroot** [comment] 2021-01-01 21:38
OK, I do not get this report... it seems that the user wanna to use this plugin for something what is not the purpose?

@effone @lairdshaw

**Comment by lairdshaw** [comment] 2021-01-01 22:23
I can't reproduce it; I'm not even sure how to get HTML to render in posts. But the MyCode equivalent seems to work fine: enclosing an `img` tag in a `url` tag: I'm correctly directed to the `url` when I click on it.

The second bug mentioned in that post I _have_ been able to reproduce though.

**Comment by lairdshaw** [comment] 2021-01-02 02:21
OK, I've looked into this more carefully. I can now reproduce it both with MyCode (`img` tag nested in `url` tag) and HTML when allowing HTML for the forum containing the thread (`img` tag nested in `a` tag).

The reason I couldn't reproduce it for my previous comment was that the image URL that I used didn't end in a recognised image extension (it referenced `attachment.php` instead).

Bottom line: this bug occurs due to the `mybbfancybox_post()` PHP function, which in my view has no legitimate purpose, and should be removed.

Why?

1. It detects only images within `a` tags, where presumably the `a` tag was included by the poster for a purpose that shouldn't be overridden by FancyBox.
2. For images not enclosed in an `a` tag, `mybbfancybox.js` already auto-adds an `a` wrapper (in its `init()` method), so even if we rewrote the PHP `mybbfancybox_post()` function to do only that, it would be redundant.

**Comment by lairdshaw** [comment] 2021-01-02 02:24
Anyhow, that function is controlled by the `Detect image URL links?` setting, so perhaps it can just be left as-is, however in that case I'd recommend that that setting be defaulted to `No` instead of (as it currently is) `Yes`.

**Comment by lairdshaw** [comment] 2021-01-02 02:36
> so perhaps it can just be left as-is

Actually, no - the function is broken as-is. It suffers from the bug reported in #67.

**Comment by Eldenroot** [comment] 2021-01-02 10:52
> Anyhow, that function is controlled by the `Detect image URL links?` setting, so perhaps it can just be left as-is, however in that case I'd recommend that that setting be defaulted to `No` instead of (as it currently is) `Yes`.

OK, I agree. And also maybe add a note into ACP setting that this feature is experimental.

**Comment by lairdshaw** [comment] 2021-01-02 15:24
Ah, nevermind, I figured out what this setting/function is supposed to be doing:

It's supposed to be detecting `a` tags whose `href` attribute points to an image.

The fact that it _also_ detects `a` tags whose `href` does _not_ point to an image, but which _enclose_ an `img` tag is unintended, and is the _actual_ bug.

This can be fixed by improving the regex pattern and how it is replaced.

I'll share a PR shortly.

**Closed** 2021-01-02 17:11 UTC
Labels: bug, help wanted, question
